STACKING

In [2]:
import numpy as np

Condition : Array should be of same size 

In [3]:
# Stacking: stacking up/joining two or more arrays into one -->horizontal -->vertical

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
# 1. horizontal : .hstack(())
np.hstack((a1,a2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [5]:
np.hstack((a1,a2,a1))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [6]:
# 2. vertical : .vstack(())
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
np.vstack((a1,a2,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

SPLITING : reverse functionality of stacking

In [18]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

# horizontal split
np.hsplit(a1,2)
np.hsplit(a2,4)


[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [17]:
# Vertical split
np.vsplit(a2,3)
np.vsplit(a1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]