ARRAY FUNCTIONS 

In [1]:
import numpy as np

In [2]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[43., 81., 18.],
       [91., 65., 50.],
       [77., 66., 39.]])

max/min/sum/prod

In [23]:
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
# For every row or column find max/min/sum/prod
# axis = 0 -> y-axis/ col
# axis = 1 -> x-axis/ row
np.max(a1,axis=1)
np.min(a1,axis=0)

np.prod(a1,axis=1)

array([422370.,   7068.,  13860.])

mean/median/std/var


In [10]:
np.mean(a1)
np.mean(a1,axis=1)

np.median(a1)
np.median(a1,axis=1)


np.std(a1)
np.std(a1,axis=1)

np.var(a1)
np.var(a1,axis=1)

array([670.88888889, 286.88888889, 254.88888889])

TRIGONOMETRIC FUNCTIONS: sim/cos/tan

In [ ]:
np.cos(a1)
np.sin(a1)
np.tan(a1)

array([[-6.67384176e-01, -1.23305411e+00, -8.79264876e-01],
       [-9.38193042e+00, -6.80254405e-01, -3.67781445e+00],
       [-3.09899020e-02,  3.76498684e+01,  2.76659275e-01]])

dot product: no. of col = no. of row
-->shape: row of 1st * col of 2nd

In [18]:
a2 =  np.arange(12).reshape(3,4)
a3 =  np.arange(12).reshape(4,3)

print(a2)
print()
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

log and exponential 

In [22]:
print(a1)
np.log(a1)
np.exp(a1)


[[43. 81. 18.]
 [91. 65. 50.]
 [77. 66. 39.]]


array([[4.72783947e+18, 1.50609731e+35, 6.56599691e+07],
       [3.31740010e+39, 1.69488924e+28, 5.18470553e+21],
       [2.75851345e+33, 4.60718663e+28, 8.65934004e+16]])

round/floor/ceil

In [32]:
r = np.random.random((3,4))*100
np.round(r)
np.floor(r)
np.ceil(r)

array([[19., 81., 98., 52.],
       [80., 77.,  6., 70.],
       [83.,  8., 92., 67.]])