ARRAY OPERATIONS

In [2]:
import numpy as np

In [5]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4) 

In [7]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Operations : Scalar oprations And Vector Operations

In [ ]:
# Scalar operations

# 1. Arthemtic 
a1*2 # like matrix scalar multiplication
a1**2
a1/2
a1//2
a1+2
a1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
# Relational operator(>,<,>=,<=,!=,==)
a1>6
a2>=19
a2<10
a2==21


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

VECTOR OPERATIONS :

In [31]:
# Arthemtic operations: Shape of the both array should be same  
print(a1)
print()
print(a2)

#  matrix addition
a1+a2
#  matrix subrtactiom
a1-a2

# element wise multiplication
a1*a2


# Relational: 
a1<a2
a1>=a2
a1==a2


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])