ARRAY ATTRIBUTES

In [1]:
import numpy as np

In [3]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [5]:
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


<!-- ndim: No. of n dimensional array  -->

In [8]:
a1.ndim
a2.ndim
a3.ndim

3

<!-- shape:no. of rows and columns/no. of items -->

In [42]:
a1.shape
a2.shape
a3.shape

(2, 2, 2)

<!-- size :total no of items in arrays -->

In [15]:
a1.size
a2.size
a3.size

8

<!-- itemsize : size of item in the memory  -->

In [21]:
a1.itemsize
a2.itemsize
a3.itemsize
a1 = np.arange(10,dtype=np.int32)
a1.itemsize


4

<!-- dtype : type of array -->

In [25]:

a2.dtype
a3.dtype
a1.dtype

dtype('int32')

<!-- astype : to change the data type of an exisitng array -->

In [40]:
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)