INDEX AND SLICING


In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [3]:
print(a1)
print()
print(a2)
print()
print(a1)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# same a list: 1d array
a1[-1]
a1[4]
a1[4:9]

array([4, 5, 6, 7, 8])

In [5]:
# In 2d index and slicing is done by rows and columns
print(a2)
# a2[row_no,col_no] : fetch 7 row start =0 col =0
a2[1,3]
a2[2,3]
a2[1,0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(4)

In [6]:
#  3d index or slicing
print(a3)
#  0
a3[0,0,0]
# 7
a3[1,1,1]
#  3
a3[0,1,1]
# 5
a3[1,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


np.int64(5)

SLICING

In [7]:
print(a1)
a1[2:5]
a1[2:5:2]
a1[::-1]


[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
# 2D slicing
print(a2)

#first row 
a2[0,:]

# 3rd column
a2[:,2]

# 5,6,9,10
a2[1:,1:3]

# 3,8,11
a2[::2,::3]

# 1,3,9,11
a2[::2,1::2]

# 4,7
a2[1,::3]

# 1,2,3,5,6,7
a2[:2,1:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1, 2, 3],
       [5, 6, 7]])

3D SLICING

In [9]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
a3[::2]
a3[0,1:2,:]
a3[1,:,1]

a3[2,1:,1:]

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])