RESHAPING

In [3]:
import numpy as np

In [8]:
# reshape
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# transpose 
a = a.reshape(3,4)
a
# 1
np.transpose(a)
# 2
a.T

a2 = np.arange(10)
np.transpose(a2) # -> same as before

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

.ravel(): Convert any dimensions of array into one dimensional array

In [19]:
r = np.arange(27).reshape(3,3,3)
print(r)

r.ravel()

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])